apiVersion: v2
appVersion: '1.0'
description: Example for geoserver-cloud with pgconfig
name: gs-cloud-pgconfig
version: 0.1.0
dependencies:
  - name: 'geoservercloud'
    repository: https://camptocamp.github.io/helm-geoserver-cloud
    version: 2.3.0
  - name: 'rabbitmq'
    version: 15.0.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: rabbitmq.enabled
  - name: 'postgresql'
    version: 14.0.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
  - name: 'pgbouncer'
    repository: https://icoretech.github.io/helm
    version: 2.3.2
